apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-5cb5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-5cb5
    app.kubernetes.io/part-of: test-app-791
  name: retrodep-5cb5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-5cb5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-5cb5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-791/retrodep-5cb5@sha256:27e591d49927ea11895b2c445133bbbb0d9309c32da165374283551c40d90222
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
