apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-rj76
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-from-registry-rh-io-rj76
    app.kubernetes.io/part-of: test-app-791
  name: e2e-tests-parent-image-from-registry-rh-io-rj76
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-rj76
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-rj76
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-791/e2e-tests-parent-image-from-registry-rh-io-rj76@sha256:af0165639e7923dbce3f84f9e23ff9b1e567627fdd2b15b2c5a63a6b3a2b6d01
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
