apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-m6om
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-both-tag-digest-m6om
    app.kubernetes.io/part-of: test-app-791
  name: e2e-tests-parent-image-with-both-tag-digest-m6om
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-m6om
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-m6om
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-791/e2e-tests-parent-image-with-both-tag-digest-m6om@sha256:2df19b29a4d7d58e8f5ea3eb1d54e76625deea1eeaa3520b976710509332179b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
