apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-srgy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-srgy
    app.kubernetes.io/part-of: test-app-791
  name: e2e-tests-parent-image-with-digest-only-srgy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-srgy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-srgy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-791/e2e-tests-parent-image-with-digest-only-srgy@sha256:cdd5b642bca11f3d3672495466a3b3682caaa07072d9d63a30593130e13c979f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
