apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-fpsx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-fpsx
    app.kubernetes.io/part-of: test-app-791
  name: maven-hello-world-fpsx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-fpsx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-fpsx
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-791/maven-hello-world-fpsx@sha256:18fc413926b6dd5066c748972487c1b4e5dd3c85c00d51caeb116555bbb6a545
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
